services:
  redis:
    image: redis:6-alpine
    container_name: redis_server
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    container_name: flask_app
    depends_on:
      - redis
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ~/.ssh:/home/appuser/.ssh
    env_file:
      - .env
    user: "${HOST_UID}:${HOST_GID}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery:
    build:
      context: .
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    container_name: celery_worker
    depends_on:
      - redis
      - web
    volumes:
      - .:/app
      - ~/.ssh:/home/appuser/.ssh
    env_file:
      - .env
    user: "${HOST_UID}:${HOST_GID}"
    command: celery -A celery_worker.celery worker --loglevel=info
