version: '3.8'

services:
  redis:
    image: redis:6-alpine
    container_name: redis_server
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: flask_app
    depends_on:
      - redis
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - dbdata:/app/db
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:////app/db/db.sqlite3
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery:
    build: .
    container_name: celery_worker
    depends_on:
      - redis
      - web
    volumes:
      - .:/app
      - dbdata:/app/db
    environment:
      - DATABASE_URL=sqlite:////app/db/db.sqlite3
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A celery_worker.celery worker --loglevel=info

volumes:
  dbdata: