version: '3.8'

services:
  redis:
    image: redis:6-alpine
    container_name: redis_server
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: flask_app
    depends_on:
      - redis
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - sqlite_data:/app/db
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery:
    build: .
    container_name: celery_worker
    depends_on:
      - redis
      - web
    volumes:
      - .:/app
      - sqlite_data:/app/db
    env_file:
      - .env
    command: celery -A celery_worker.celery worker --loglevel=info

volumes:
  sqlite_data:
